### ISSUE TITLE
TypeError: h.filter is not a function

### ISSUE THREAD

**Issue by sirdrakeistda** [bigbluebutton/bbb-install#691]
I tried to install bigbluebutton 2.7 on a fresh server. There are no detected potential problems, but I get a blue window after joining the server. In my browser console I see following error message:

`
Uncaught TypeError: h.filter is not a function
    e https://domain.de/html5client/11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:680
    g https://domain.de/html5client/11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:7
    r https://domain.de/html5client/11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:7
    o https://domain.de/html5client/11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:9
`
How do I solve this error?

bbb-conf --status shows that all services are active

**Comment by BernhardFahr** [comment]
Same constellation. Error:

Uncaught TypeError: h.filter is not a function
    at e (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:680:1277546)
    at g (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:7:1100)
    at d.r [as require] (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:7:3658)
    at d.o [as link] (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:9:3372)
    at e (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:680:484048)
    at g (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:7:1100)
    at d.r [as require] (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:7:3658)
    at d.o [as link] (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:9:3372)
    at e (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:680:972832)
    at g (11c7ff844f98e0e76abb1f715bdf2a2c52b2fdb6.js?meteor_js_resource=true:7:1100)

**Comment by leManu** [comment]
Hi, same problem here, just installed bigbluebutton 2.7 on a fresh machine, same error in browser console and empty dark blue page on /html5client/join uri.

Bigbluebutton 2.6 installed the same way works nicely. I'm going to test upgrade to 2.7 afterward to see if it works...

**Comment by leManu** [comment]
After upgrading 2.6 to 2.7 using bbb-install.sh same problem, empty dark blue page and brower console error :disappointed: :

`
Uncaught TypeError: h.filter is not a function
`

**Comment by ffdixon** [comment]
Can you check `/etc/bigbluebutton/bbb-html.yml` and see

```
    cameraProfiles: {}
```

Do you have anything in `/etc/bigbluebutton/bbb-conf/apply-config.sh` that tries to set the `cameraProfiles`.   If so, try removing it, and editing `/etc/bigbluebutton/bbb-html.yml` to remove `cameraProfiles: {}`, then restarting BigBlueButton and see if you can now join.

**Comment by sirdrakeistda** [comment]
I removed the line `cameraProfiles: {}` and now it seems working. The brackets were empty.

**Comment by BernhardFahr** [comment]
Helped like a charm 👍 
Thank you!!!

**Comment by vlasov01** [comment]
Thank you a lot!  I think there is a small typo. The file name to edit and remove cameraProfiles is /etc/bigbluebutton/bbb-html5.yml and not /etc/bigbluebutton/bbb-html.yml  .
